### PR TITLE
testing quarantined

### PR DESCRIPTION
**Pull request by r4ddek**

### CODE REVIEW

**Comment by r4ddek** [comment]
ci:test:analytics-cloud:nocompile

**Comment by r4ddek** [comment]
ci:test:analytics-cloud:nocompile

**Comment by ViniLopes20** [comment]
ci:test:sf

**Comment by r4ddek** [comment]
ci:test:analytics-cloud:nocompile

**Comment by ViniLopes20** [comment]
ci:test:sf

**Pull request closed without merging**
